name: Schedule index.js Execution

on:
  schedule:
    - cron: "0 9 * * 1,3,5"
  workflow_dispatch:

jobs:
  run_index_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run post-to-discord.js
        run: node post-to-discord.js
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
